//========================================================================
// GLFW 3.3 - www.glfw.org
//------------------------------------------------------------------------
// Copyright (c) 2017-2018 Volcano Authors <volcano.authors@gmail.com>
//
// This file contains _glfwPlatformAndroidHandleEvent() and related functions.

#include "internal.h"

#include <android_native_app_glue.h>
#include <android/log.h>

const char* _glfwPlatformGetScancodeName(int scancode)
{
    _glfwInputError(
        GLFW_INVALID_ENUM,
        "Android NDK specifies: hardware scan code is not reliable and "
        "varies from device to device");
    return NULL;
}

int _glfwPlatformGetKeyScancode(int key)
{
    _glfwInputError(
        GLFW_INVALID_ENUM,
        "Android NDK specifies: hardware scan code is not reliable and "
        "varies from device to device");
    return GLFW_RELEASE;
}

int androidToGLFWkey(int androidKeyCode, int* plain) {
#define ANDROID_KEY_TO_GLFW(x) \
  case AKEYCODE_##x: return GLFW_KEY_##x;

#define ANDROID_KEY_IGNORED(x) \
  case AKEYCODE_##x: return GLFW_KEY_UNKNOWN;

  switch (androidKeyCode) {
    ANDROID_KEY_TO_GLFW(0);
    ANDROID_KEY_TO_GLFW(1);
    ANDROID_KEY_TO_GLFW(2);
    ANDROID_KEY_TO_GLFW(3);
    ANDROID_KEY_TO_GLFW(4);
    ANDROID_KEY_TO_GLFW(5);
    ANDROID_KEY_TO_GLFW(6);
    ANDROID_KEY_TO_GLFW(7);
    ANDROID_KEY_TO_GLFW(8);
    ANDROID_KEY_TO_GLFW(9);
    ANDROID_KEY_TO_GLFW(A);
    ANDROID_KEY_TO_GLFW(B);
    ANDROID_KEY_TO_GLFW(C);
    ANDROID_KEY_TO_GLFW(D);
    ANDROID_KEY_TO_GLFW(E);
    ANDROID_KEY_TO_GLFW(F);
    ANDROID_KEY_TO_GLFW(G);
    ANDROID_KEY_TO_GLFW(H);
    ANDROID_KEY_TO_GLFW(I);
    ANDROID_KEY_TO_GLFW(J);
    ANDROID_KEY_TO_GLFW(K);
    ANDROID_KEY_TO_GLFW(L);
    ANDROID_KEY_TO_GLFW(M);
    ANDROID_KEY_TO_GLFW(N);
    ANDROID_KEY_TO_GLFW(O);
    ANDROID_KEY_TO_GLFW(P);
    ANDROID_KEY_TO_GLFW(Q);
    ANDROID_KEY_TO_GLFW(R);
    ANDROID_KEY_TO_GLFW(S);
    ANDROID_KEY_TO_GLFW(T);
    ANDROID_KEY_TO_GLFW(U);
    ANDROID_KEY_TO_GLFW(V);
    ANDROID_KEY_TO_GLFW(W);
    ANDROID_KEY_TO_GLFW(X);
    ANDROID_KEY_TO_GLFW(Y);
    ANDROID_KEY_TO_GLFW(Z);
    ANDROID_KEY_TO_GLFW(COMMA);
    ANDROID_KEY_TO_GLFW(PERIOD);
    case AKEYCODE_ALT_LEFT: *plain = GLFW_FALSE; return GLFW_KEY_LEFT_ALT;
    case AKEYCODE_ALT_RIGHT: *plain = GLFW_FALSE; return GLFW_KEY_RIGHT_ALT;
    case AKEYCODE_SHIFT_LEFT: *plain = GLFW_FALSE; return GLFW_KEY_LEFT_SHIFT;
    case AKEYCODE_SHIFT_RIGHT: *plain = GLFW_FALSE; return GLFW_KEY_RIGHT_SHIFT;
    case AKEYCODE_CTRL_LEFT: *plain = GLFW_FALSE; return GLFW_KEY_LEFT_CONTROL;
    case AKEYCODE_CTRL_RIGHT: *plain = GLFW_FALSE; return GLFW_KEY_RIGHT_CONTROL;
    case AKEYCODE_CAPS_LOCK: *plain = GLFW_FALSE; return GLFW_KEY_CAPS_LOCK;
    case AKEYCODE_SCROLL_LOCK: *plain = GLFW_FALSE; return GLFW_KEY_SCROLL_LOCK;
    case AKEYCODE_NUM_LOCK: *plain = GLFW_FALSE; return GLFW_KEY_NUM_LOCK;
    case AKEYCODE_META_LEFT: *plain = GLFW_FALSE; return GLFW_KEY_LEFT_SUPER;
    case AKEYCODE_META_RIGHT: *plain = GLFW_FALSE; return GLFW_KEY_RIGHT_SUPER;
    case AKEYCODE_SYSRQ: *plain = GLFW_FALSE; return GLFW_KEY_PRINT_SCREEN;
    case AKEYCODE_BREAK: *plain = GLFW_FALSE; return GLFW_KEY_PAUSE;
    case AKEYCODE_MENU: *plain = GLFW_FALSE; return GLFW_KEY_MENU;
    ANDROID_KEY_TO_GLFW(TAB);
    ANDROID_KEY_TO_GLFW(SPACE);
    ANDROID_KEY_TO_GLFW(ENTER);
    case AKEYCODE_DEL: *plain = GLFW_FALSE; return GLFW_KEY_BACKSPACE;
    case AKEYCODE_FORWARD_DEL: *plain = GLFW_FALSE; return GLFW_KEY_DELETE;
    case AKEYCODE_GRAVE: return GLFW_KEY_GRAVE_ACCENT;
    ANDROID_KEY_TO_GLFW(MINUS);
    case AKEYCODE_EQUALS: return GLFW_KEY_EQUAL;
    ANDROID_KEY_TO_GLFW(LEFT_BRACKET);
    ANDROID_KEY_TO_GLFW(RIGHT_BRACKET);
    ANDROID_KEY_TO_GLFW(BACKSLASH);
    ANDROID_KEY_TO_GLFW(SEMICOLON);
    ANDROID_KEY_TO_GLFW(APOSTROPHE);
    ANDROID_KEY_TO_GLFW(SLASH);
    case AKEYCODE_PAGE_UP: *plain = GLFW_FALSE; return GLFW_KEY_PAGE_UP;
    case AKEYCODE_PAGE_DOWN: *plain = GLFW_FALSE; return GLFW_KEY_PAGE_DOWN;
    case AKEYCODE_ESCAPE: *plain = GLFW_FALSE; return GLFW_KEY_ESCAPE;
    case AKEYCODE_INSERT: *plain = GLFW_FALSE; return GLFW_KEY_INSERT;
    case AKEYCODE_F1: *plain = GLFW_FALSE; return GLFW_KEY_F1;
    case AKEYCODE_F2: *plain = GLFW_FALSE; return GLFW_KEY_F2;
    case AKEYCODE_F3: *plain = GLFW_FALSE; return GLFW_KEY_F3;
    case AKEYCODE_F4: *plain = GLFW_FALSE; return GLFW_KEY_F4;
    case AKEYCODE_F5: *plain = GLFW_FALSE; return GLFW_KEY_F5;
    case AKEYCODE_F6: *plain = GLFW_FALSE; return GLFW_KEY_F6;
    case AKEYCODE_F7: *plain = GLFW_FALSE; return GLFW_KEY_F7;
    case AKEYCODE_F8: *plain = GLFW_FALSE; return GLFW_KEY_F8;
    case AKEYCODE_F9: *plain = GLFW_FALSE; return GLFW_KEY_F9;
    case AKEYCODE_F10: *plain = GLFW_FALSE; return GLFW_KEY_F10;
    case AKEYCODE_F11: *plain = GLFW_FALSE; return GLFW_KEY_F11;
    case AKEYCODE_F12: *plain = GLFW_FALSE; return GLFW_KEY_F12;
    case AKEYCODE_DPAD_UP: *plain = GLFW_FALSE; return GLFW_KEY_UP;
    case AKEYCODE_DPAD_DOWN: *plain = GLFW_FALSE; return GLFW_KEY_DOWN;
    case AKEYCODE_DPAD_LEFT: *plain = GLFW_FALSE; return GLFW_KEY_LEFT;
    case AKEYCODE_DPAD_RIGHT: *plain = GLFW_FALSE; return GLFW_KEY_RIGHT;
    case AKEYCODE_MOVE_HOME: *plain = GLFW_FALSE; return GLFW_KEY_HOME;
    case AKEYCODE_MOVE_END: *plain = GLFW_FALSE; return GLFW_KEY_END;
    case AKEYCODE_NUMPAD_0: return GLFW_KEY_KP_0;
    case AKEYCODE_NUMPAD_1: return GLFW_KEY_KP_1;
    case AKEYCODE_NUMPAD_2: return GLFW_KEY_KP_2;
    case AKEYCODE_NUMPAD_3: return GLFW_KEY_KP_3;
    case AKEYCODE_NUMPAD_4: return GLFW_KEY_KP_4;
    case AKEYCODE_NUMPAD_5: return GLFW_KEY_KP_5;
    case AKEYCODE_NUMPAD_6: return GLFW_KEY_KP_6;
    case AKEYCODE_NUMPAD_7: return GLFW_KEY_KP_7;
    case AKEYCODE_NUMPAD_8: return GLFW_KEY_KP_8;
    case AKEYCODE_NUMPAD_9: return GLFW_KEY_KP_9;
    case AKEYCODE_NUMPAD_DIVIDE: return GLFW_KEY_KP_DIVIDE;
    case AKEYCODE_NUMPAD_MULTIPLY: return GLFW_KEY_KP_MULTIPLY;
    case AKEYCODE_NUMPAD_SUBTRACT: return GLFW_KEY_KP_SUBTRACT;
    case AKEYCODE_NUMPAD_ADD: return GLFW_KEY_KP_ADD;
    case AKEYCODE_NUMPAD_DOT: return GLFW_KEY_KP_DECIMAL;
    case AKEYCODE_NUMPAD_ENTER: return GLFW_KEY_KP_ENTER;
    case AKEYCODE_NUMPAD_EQUALS: return GLFW_KEY_KP_EQUAL;

    // Map F13-F25 to some android keys, arbitrarily.
    case AKEYCODE_SOFT_LEFT: return GLFW_KEY_F13;
    case AKEYCODE_SOFT_RIGHT: return GLFW_KEY_F14;
    case AKEYCODE_DPAD_CENTER: return GLFW_KEY_F15;
    case AKEYCODE_HOME: return GLFW_KEY_F16;
    case AKEYCODE_BACK: return GLFW_KEY_F17;
    case AKEYCODE_SEARCH: return GLFW_KEY_F18;
    case AKEYCODE_MEDIA_PLAY_PAUSE: return GLFW_KEY_F19;
    case AKEYCODE_MEDIA_STOP: return GLFW_KEY_F20;
    case AKEYCODE_MEDIA_REWIND: return GLFW_KEY_F21;
    case AKEYCODE_MEDIA_FAST_FORWARD: return GLFW_KEY_F22;
    case AKEYCODE_MEDIA_PLAY: return GLFW_KEY_F23;
    case AKEYCODE_MEDIA_PAUSE: return GLFW_KEY_F24;
    case AKEYCODE_MUTE: return GLFW_KEY_F25;

    ANDROID_KEY_IGNORED(MEDIA_RECORD);
    ANDROID_KEY_IGNORED(FORWARD);
    ANDROID_KEY_IGNORED(MEDIA_NEXT);
    ANDROID_KEY_IGNORED(MEDIA_PREVIOUS);
    ANDROID_KEY_IGNORED(MEDIA_CLOSE);
    ANDROID_KEY_IGNORED(MEDIA_EJECT);
    ANDROID_KEY_IGNORED(MEDIA_AUDIO_TRACK);
    ANDROID_KEY_IGNORED(MEDIA_TOP_MENU);
    ANDROID_KEY_IGNORED(CALL);
    ANDROID_KEY_IGNORED(ENDCALL);
    ANDROID_KEY_IGNORED(HEADSETHOOK);
    ANDROID_KEY_IGNORED(FOCUS);
    ANDROID_KEY_IGNORED(NOTIFICATION);
    ANDROID_KEY_IGNORED(PLUS);
    ANDROID_KEY_IGNORED(STAR);
    ANDROID_KEY_IGNORED(POUND);
    ANDROID_KEY_IGNORED(VOLUME_UP);
    ANDROID_KEY_IGNORED(VOLUME_DOWN);
    ANDROID_KEY_IGNORED(VOLUME_MUTE);
    ANDROID_KEY_IGNORED(POWER);
    ANDROID_KEY_IGNORED(CAMERA);
    ANDROID_KEY_IGNORED(CLEAR);
    ANDROID_KEY_IGNORED(SYM);
    ANDROID_KEY_IGNORED(EXPLORER);
    ANDROID_KEY_IGNORED(ENVELOPE);
    ANDROID_KEY_IGNORED(AT);
    ANDROID_KEY_IGNORED(NUM);
    ANDROID_KEY_IGNORED(PICTSYMBOLS);
    ANDROID_KEY_IGNORED(SWITCH_CHARSET);
    ANDROID_KEY_IGNORED(BUTTON_A);
    ANDROID_KEY_IGNORED(BUTTON_B);
    ANDROID_KEY_IGNORED(BUTTON_C);
    ANDROID_KEY_IGNORED(BUTTON_X);
    ANDROID_KEY_IGNORED(BUTTON_Y);
    ANDROID_KEY_IGNORED(BUTTON_Z);
    ANDROID_KEY_IGNORED(BUTTON_L1);
    ANDROID_KEY_IGNORED(BUTTON_R1);
    ANDROID_KEY_IGNORED(BUTTON_L2);
    ANDROID_KEY_IGNORED(BUTTON_R2);
    ANDROID_KEY_IGNORED(BUTTON_THUMBL);
    ANDROID_KEY_IGNORED(BUTTON_THUMBR);
    ANDROID_KEY_IGNORED(BUTTON_START);
    ANDROID_KEY_IGNORED(BUTTON_SELECT);
    ANDROID_KEY_IGNORED(BUTTON_MODE);
    ANDROID_KEY_IGNORED(FUNCTION);
    ANDROID_KEY_IGNORED(LAST_CHANNEL);
    ANDROID_KEY_IGNORED(TV_DATA_SERVICE);
    ANDROID_KEY_IGNORED(VOICE_ASSIST);
    ANDROID_KEY_IGNORED(TV_RADIO_SERVICE);
    ANDROID_KEY_IGNORED(TV_TELETEXT);
    ANDROID_KEY_IGNORED(TV_NUMBER_ENTRY);
    ANDROID_KEY_IGNORED(TV_TERRESTRIAL_ANALOG);
    ANDROID_KEY_IGNORED(TV_TERRESTRIAL_DIGITAL);
    ANDROID_KEY_IGNORED(TV_SATELLITE);
    ANDROID_KEY_IGNORED(TV_SATELLITE_BS);
    ANDROID_KEY_IGNORED(TV_SATELLITE_CS);
    ANDROID_KEY_IGNORED(TV_SATELLITE_SERVICE);
    ANDROID_KEY_IGNORED(TV_NETWORK);
    ANDROID_KEY_IGNORED(TV_ANTENNA_CABLE);
    ANDROID_KEY_IGNORED(TV_INPUT_HDMI_1);
    ANDROID_KEY_IGNORED(TV_INPUT_HDMI_2);
    ANDROID_KEY_IGNORED(TV_INPUT_HDMI_3);
    ANDROID_KEY_IGNORED(TV_INPUT_HDMI_4);
    ANDROID_KEY_IGNORED(TV_INPUT_COMPOSITE_1);
    ANDROID_KEY_IGNORED(TV_INPUT_COMPOSITE_2);
    ANDROID_KEY_IGNORED(TV_INPUT_COMPONENT_1);
    ANDROID_KEY_IGNORED(TV_INPUT_COMPONENT_2);
    ANDROID_KEY_IGNORED(TV_INPUT_VGA_1);
    ANDROID_KEY_IGNORED(TV_AUDIO_DESCRIPTION);
    ANDROID_KEY_IGNORED(TV_AUDIO_DESCRIPTION_MIX_UP);
    ANDROID_KEY_IGNORED(TV_AUDIO_DESCRIPTION_MIX_DOWN);
    ANDROID_KEY_IGNORED(TV_ZOOM_MODE);
    ANDROID_KEY_IGNORED(TV_CONTENTS_MENU);
    ANDROID_KEY_IGNORED(TV_MEDIA_CONTEXT_MENU);
    ANDROID_KEY_IGNORED(TV_TIMER_PROGRAMMING);
    ANDROID_KEY_IGNORED(HELP);
    ANDROID_KEY_IGNORED(NUMPAD_COMMA);
    ANDROID_KEY_IGNORED(NUMPAD_LEFT_PAREN);
    ANDROID_KEY_IGNORED(NUMPAD_RIGHT_PAREN);
    ANDROID_KEY_IGNORED(INFO);
    ANDROID_KEY_IGNORED(CHANNEL_UP);
    ANDROID_KEY_IGNORED(CHANNEL_DOWN);
    ANDROID_KEY_IGNORED(ZOOM_IN);
    ANDROID_KEY_IGNORED(ZOOM_OUT);
    ANDROID_KEY_IGNORED(TV);
    ANDROID_KEY_IGNORED(WINDOW);
    ANDROID_KEY_IGNORED(GUIDE);
    ANDROID_KEY_IGNORED(DVR);
    ANDROID_KEY_IGNORED(BOOKMARK);
    ANDROID_KEY_IGNORED(CAPTIONS);
    ANDROID_KEY_IGNORED(SETTINGS);
    ANDROID_KEY_IGNORED(TV_POWER);
    ANDROID_KEY_IGNORED(TV_INPUT);
    ANDROID_KEY_IGNORED(STB_POWER);
    ANDROID_KEY_IGNORED(STB_INPUT);
    ANDROID_KEY_IGNORED(AVR_POWER);
    ANDROID_KEY_IGNORED(AVR_INPUT);
    ANDROID_KEY_IGNORED(PROG_RED);
    ANDROID_KEY_IGNORED(PROG_GREEN);
    ANDROID_KEY_IGNORED(PROG_YELLOW);
    ANDROID_KEY_IGNORED(PROG_BLUE);
    ANDROID_KEY_IGNORED(APP_SWITCH);
    ANDROID_KEY_IGNORED(BUTTON_1);
    ANDROID_KEY_IGNORED(BUTTON_2);
    ANDROID_KEY_IGNORED(BUTTON_3);
    ANDROID_KEY_IGNORED(BUTTON_4);
    ANDROID_KEY_IGNORED(BUTTON_5);
    ANDROID_KEY_IGNORED(BUTTON_6);
    ANDROID_KEY_IGNORED(BUTTON_7);
    ANDROID_KEY_IGNORED(BUTTON_8);
    ANDROID_KEY_IGNORED(BUTTON_9);
    ANDROID_KEY_IGNORED(BUTTON_10);
    ANDROID_KEY_IGNORED(BUTTON_11);
    ANDROID_KEY_IGNORED(BUTTON_12);
    ANDROID_KEY_IGNORED(BUTTON_13);
    ANDROID_KEY_IGNORED(BUTTON_14);
    ANDROID_KEY_IGNORED(BUTTON_15);
    ANDROID_KEY_IGNORED(BUTTON_16);
    ANDROID_KEY_IGNORED(LANGUAGE_SWITCH);
    ANDROID_KEY_IGNORED(MANNER_MODE);
    ANDROID_KEY_IGNORED(3D_MODE);
    ANDROID_KEY_IGNORED(CONTACTS);
    ANDROID_KEY_IGNORED(CALENDAR);
    ANDROID_KEY_IGNORED(MUSIC);
    ANDROID_KEY_IGNORED(CALCULATOR);
    ANDROID_KEY_IGNORED(ZENKAKU_HANKAKU);
    ANDROID_KEY_IGNORED(EISU);
    ANDROID_KEY_IGNORED(MUHENKAN);
    ANDROID_KEY_IGNORED(HENKAN);
    ANDROID_KEY_IGNORED(KATAKANA_HIRAGANA);
    ANDROID_KEY_IGNORED(YEN);
    ANDROID_KEY_IGNORED(RO);
    ANDROID_KEY_IGNORED(KANA);
    ANDROID_KEY_IGNORED(ASSIST);
    ANDROID_KEY_IGNORED(BRIGHTNESS_DOWN);
    ANDROID_KEY_IGNORED(BRIGHTNESS_UP);
    ANDROID_KEY_IGNORED(SLEEP);
    ANDROID_KEY_IGNORED(WAKEUP);
    ANDROID_KEY_IGNORED(PAIRING);
    ANDROID_KEY_IGNORED(11);
    ANDROID_KEY_IGNORED(12);
  }
  return GLFW_KEY_UNKNOWN;
#undef ANDROID_KEY_TO_GLFW
#undef ANDROID_KEY_IGNORED
}

static void androidKeyToUtf32(struct android_app* app, AInputEvent* event,
                              int mods, int action, int repCount) {
  int scancode = AKeyEvent_getScanCode(event);
  int plain = GLFW_TRUE;  // This event does not describe a modifier key.
  int key = androidToGLFWkey(AKeyEvent_getKeyCode(event), &plain);

  // If action == GLFW_PRESS send _glfwInputChar also.
  int utf32 = 0;
  if (action == GLFW_PRESS && plain) {
    utf32 = jniGetUnicodeChar(event);
    if (utf32 < 0) {
      _glfwInputError(GLFW_PLATFORM_ERROR, "jniGetUnicodeChar: %lld",
                      (long long)utf32);
      utf32 = 0;  // Do not send _glfwInputChar.
    }
#define COMBINING_ACCENT (0x80000000)
    if (utf32 & COMBINING_ACCENT) {
      utf32 = 0;  // Ignore combining keys.
    }
#undef COMBINING_ACCENT
  }

  for (int i = 0; i < repCount; i++) {
    _glfwInputKey(_glfw.android.oneAndOnlyWindow, key, scancode, action, mods);
    if (utf32) {
      _glfwInputChar(_glfw.android.oneAndOnlyWindow, utf32, mods, plain);
    }
  }
}

void handleKeyEvent(struct android_app* app, AInputEvent* ev, int m) {
  switch (AKeyEvent_getAction(ev)) {
  case AKEY_EVENT_ACTION_DOWN:
    androidKeyToUtf32(app, ev, m, GLFW_PRESS, 1);
    break;
  case AKEY_EVENT_ACTION_UP:
    androidKeyToUtf32(app, ev, m, GLFW_RELEASE, 1);
    break;
  case AKEY_EVENT_ACTION_MULTIPLE:
    androidKeyToUtf32(app, ev, m, GLFW_REPEAT, AKeyEvent_getRepeatCount(ev));
    break;
  }
}
